# Form implementation generated from reading ui file 'c:\Users\omar\Documents\Python Scripts\meps2\Add_edge.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(522, 415)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(170, 85, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 87 20pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.fr = QtWidgets.QComboBox(self.centralwidget)
        self.fr.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.fr.setObjectName("fr")
        self.horizontalLayout.addWidget(self.fr)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.to = QtWidgets.QComboBox(self.centralwidget)
        self.to.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.to.setObjectName("to")
        self.horizontalLayout_2.addWidget(self.to)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.by = QtWidgets.QComboBox(self.centralwidget)
        self.by.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.by.setObjectName("by")
        self.horizontalLayout_3.addWidget(self.by)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 255);")
        self.submit.setObjectName("submit")
        self.verticalLayout.addWidget(self.submit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 522, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ADD Edge"))
        self.label_2.setText(_translate("MainWindow", "From:"))
        self.label_3.setText(_translate("MainWindow", "To:"))
        self.label_4.setText(_translate("MainWindow", "By:"))
        self.submit.setText(_translate("MainWindow", "Submit"))
