# Form implementation generated from reading ui file 'c:\Users\omar\Documents\Python Scripts\meps2\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1823, 1004)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("background-color: rgb(170, 85, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.b_add_n2 = QtWidgets.QPushButton(self.frame_3)
        self.b_add_n2.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(170, 170, 0);\n"
"border-color: rgb(85, 255, 127);")
        self.b_add_n2.setObjectName("b_add_n2")
        self.verticalLayout_3.addWidget(self.b_add_n2)
        self.b_add_e2 = QtWidgets.QPushButton(self.frame_3)
        self.b_add_e2.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(170, 170, 0);\n"
"border-color: rgb(85, 255, 127);")
        self.b_add_e2.setObjectName("b_add_e2")
        self.verticalLayout_3.addWidget(self.b_add_e2)
        self.b_new2 = QtWidgets.QPushButton(self.frame_3)
        self.b_new2.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(170, 170, 0);\n"
"border-color: rgb(85, 255, 127);")
        self.b_new2.setObjectName("b_new2")
        self.verticalLayout_3.addWidget(self.b_new2)
        self.b_open2 = QtWidgets.QPushButton(self.frame_3)
        self.b_open2.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(170, 170, 0);\n"
"border-color: rgb(85, 255, 127);")
        self.b_open2.setObjectName("b_open2")
        self.verticalLayout_3.addWidget(self.b_open2)
        self.save2 = QtWidgets.QPushButton(self.frame_3)
        self.save2.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(170, 170, 0);\n"
"border-color: rgb(85, 255, 127);\n"
"")
        self.save2.setObjectName("save2")
        self.verticalLayout_3.addWidget(self.save2)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.l2 = QtWidgets.QLabel(self.frame_3)
        self.l2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.l2.setStyleSheet("\n"
"")
        self.l2.setText("")
        self.l2.setPixmap(QtGui.QPixmap("c:\\Users\\omar\\Documents\\Python Scripts\\meps2\\A2.png"))
        self.l2.setObjectName("l2")
        self.verticalLayout_3.addWidget(self.l2)
        spacerItem = QtWidgets.QSpacerItem(20, 34, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.b_prodect = QtWidgets.QPushButton(self.frame)
        self.b_prodect.setStyleSheet("font: 87 72pt \"Arial Black\";\n"
"background-color: rgb(0, 170, 0);")
        self.b_prodect.setObjectName("b_prodect")
        self.verticalLayout_4.addWidget(self.b_prodect)
        self.save3 = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        font.setKerning(False)
        self.save3.setFont(font)
        self.save3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.save3.setMouseTracking(True)
        self.save3.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"font: 87 26pt \"Arial Black\";\n"
"background-color: rgb(170, 170, 0);\n"
"border-color: rgb(85, 255, 127);")
        self.save3.setObjectName("save3")
        self.verticalLayout_4.addWidget(self.save3)
        self.horizontalLayout.addWidget(self.frame)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgb(170, 85, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.b_add_n1 = QtWidgets.QPushButton(self.frame_2)
        self.b_add_n1.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(170, 170, 0);\n"
"border-color: rgb(85, 255, 127);")
        self.b_add_n1.setObjectName("b_add_n1")
        self.verticalLayout_2.addWidget(self.b_add_n1)
        self.b_add_e1 = QtWidgets.QPushButton(self.frame_2)
        self.b_add_e1.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(170, 170, 0);\n"
"border-color: rgb(85, 255, 127);")
        self.b_add_e1.setObjectName("b_add_e1")
        self.verticalLayout_2.addWidget(self.b_add_e1)
        self.b_new1 = QtWidgets.QPushButton(self.frame_2)
        self.b_new1.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(170, 170, 0);\n"
"border-color: rgb(85, 255, 127);")
        self.b_new1.setObjectName("b_new1")
        self.verticalLayout_2.addWidget(self.b_new1)
        self.b_open1 = QtWidgets.QPushButton(self.frame_2)
        self.b_open1.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(170, 170, 0);\n"
"border-color: rgb(85, 255, 127);")
        self.b_open1.setObjectName("b_open1")
        self.verticalLayout_2.addWidget(self.b_open1)
        self.save1 = QtWidgets.QPushButton(self.frame_2)
        self.save1.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(170, 170, 0);\n"
"border-color: rgb(85, 255, 127);")
        self.save1.setObjectName("save1")
        self.verticalLayout_2.addWidget(self.save1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setMaximumSize(QtCore.QSize(400, 300))
        self.label_4.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.l1 = QtWidgets.QLabel(self.frame_2)
        self.l1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.l1.setStyleSheet("")
        self.l1.setText("")
        self.l1.setPixmap(QtGui.QPixmap("c:\\Users\\omar\\Documents\\Python Scripts\\meps2\\A1.png"))
        self.l1.setObjectName("l1")
        self.verticalLayout_2.addWidget(self.l1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 34, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setMinimumSize(QtCore.QSize(1650, 0))
        self.l3.setMaximumSize(QtCore.QSize(16777215, 400))
        self.l3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.l3.setToolTip("")
        self.l3.setStyleSheet("")
        self.l3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.l3.setText("")
        self.l3.setPixmap(QtGui.QPixmap("c:\\Users\\omar\\Documents\\Python Scripts\\meps2\\A3.png"))
        self.l3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.l3.setWordWrap(False)
        self.l3.setObjectName("l3")
        self.verticalLayout.addWidget(self.l3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_add_n2.setText(_translate("MainWindow", "add node"))
        self.b_add_e2.setText(_translate("MainWindow", "add edge"))
        self.b_new2.setText(_translate("MainWindow", "new"))
        self.b_open2.setText(_translate("MainWindow", "open"))
        self.save2.setText(_translate("MainWindow", "SAVE"))
        self.label_6.setText(_translate("MainWindow", "Automata 2"))
        self.b_prodect.setText(_translate("MainWindow", "X"))
        self.save3.setText(_translate("MainWindow", "Save"))
        self.b_add_n1.setText(_translate("MainWindow", "add node"))
        self.b_add_e1.setText(_translate("MainWindow", "add edge"))
        self.b_new1.setText(_translate("MainWindow", "new"))
        self.b_open1.setText(_translate("MainWindow", "open"))
        self.save1.setText(_translate("MainWindow", "SAVE"))
        self.label_4.setText(_translate("MainWindow", "Automata 1"))
